server:
  port: 7777
  context-path: /auth
security:
  basic:
    enabled: false

spring:
  thymeleaf:
    cache: false
  datasource:
    password: 1
    username: postgres
    url: jdbc:postgresql://localhost:5433/oauth2-server
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
